export const SEARCHFOCUS = 'search_focus'
export const SEARCHBLUR = 'search_blur'
export const INITSEARCHLIST = 'init_search_list'
export const SEARCHMOUSEIN = 'search_mouse_in'
export const SEARCHMOUSEOUT = 'search_mouse_out'
export const CHANGESEARCHLIST = 'change_search_list'